# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /fpga/xuppl4_ibert_ultrascale_gty_0_ex/imports/example_ibert_ultrascale_gty_0.xdc

# XDC: /fpga/xuppl4_ibert_ultrascale_gty_0_ex/imports/ibert_ultrascale_gty_ip_example.xdc

# IP: ip/ibert_ultrascale_gty_0/ibert_ultrascale_gty_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ibert_ultrascale_gty_0 || ORIG_REF_NAME==ibert_ultrascale_gty_0} -quiet] -quiet
